global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    architecture: 'monolithic'
    project: 'sasps-hotel-booking'
    environment: 'development'

scrape_configs:
  - job_name: 'hotel-booking-monolith'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    scrape_timeout: 4s
    static_configs:
      - targets: ['app:8080']
        labels:
          application: 'hotel-booking-monolith'
          architecture: 'monolithic'
          type: 'single-process'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          application: 'prometheus'
